version: '3.1'

services:
  calculator-frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ../frontend:/var/www/html
      
  calculator-backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "3002:80"
    links:
      - calculator-mysql:mysql
    volumes:
      - ../backend:/var/www/html

  calculator-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=calculator
      - MYSQL_ROOT_PASSWORD=nopass
    volumes:
      - CalculatorMysqlData:/var/lib/mysql/
    ports:
      - "3306:3306"

volumes:
  CalculatorMysqlData:
